deliver-sms:
  only:
    - schedules
  before_script:
    - bundle install
  script:
    - bundle exec rake deliver_today
    - sleep 100
    - bundle exec rake deliver_tomorrow
    - sleep 200
    - bundle exec rake deliver_others
