
# heroku:
#   stage: deploy
#   script:
#     - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/weather-daddy.git master

check_cache:
  image: "ruby:2.5"
  before_script:
    - apt-get update -qq && apt-get install -y telnet tree
    - ruby -v
    - bundle install -j $(nproc) --path vendor
    - tree vendor
  script:
     - telnet smtp.qq.com 587



deliver_today:
  only:
    - schedules
  # cache:
  #   paths:
  #     - vendor
  before_script:
    - ruby -v
    - bundle install -j $(nproc) --path vendor
    - ls -lahR vendor
  script:
    # - telnet smtp.qq.com 587
    - bundle exec rake deliver_today



deliver_tomorrow:
  only:
    - schedules
  # cache:
  #   paths:
  #     - vendor
  before_script:
    - ruby -v
    - bundle install -j $(nproc) --path vendor
    - ls -lahR vendor/*
  script:
    - bundle exec rake deliver_tomorrow



deliver_others:
  only:
    - schedules
  # cache:
  #   paths:
  #     - vendor
  before_script:
    - ruby -v
    - bundle install -j $(nproc) --path vendor
    - ls -lahR vendor/*
  script:
    - bundle exec rake deliver_others
